### ISSUE TITLE
OTP Check failed error

### ISSUE THREAD

**Issue by illyaom19** [rei-vilo/PDLS_Basic#1]
**Describe the bug**
When calling screen.begin(), the ESP32 crashes, and the following error message appears in the serial monitor:

```
hV _ OTP check failed - Bank 1, first 0xff, expected 0xa5
hV _ Exit with code 1  
```

This issue did not occur when using PDLS_Basic 7.x, but started happening with version 8.0+. The error occurs inside the PDLS_Common library and may be related to SPI communication or an OTP memory check.

**To Reproduce**

1. Power on the ESP32 and initialize the screen using screen.begin();
2. Observe the serial monitor output for the OTP error message.
3. The ESP32 crashes and execution halts.

**Expected behavior**
The screen should initialize correctly without crashing the ESP32.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - IDE: Arduino IDE 2.3.4
 - Version: 2.3.4

**Boards (please complete the following information):**
 - Controller: Freenove ESP32 WROOM DevKit
 - Extension board: EXT3-1
 - EPD panel iTC 2.71 BW
 - Reference SE2271KS0C1

**Additional context**
Libraries Used:

- Pervasive_Wide_Small (9.0.2) – Driver (sends content of the frame buffer to the screen)
- PDLS_Basic (9.0.5) – Screen (generates images in the frame buffer)
- PDLS_Common (9.0.6)

Findings:

- The error occurs when screen.begin() is executed, specifically in the PDLS_Common library.
- The message hV _ OTP check failed - Bank 1, first 0xff, expected 0xa5 is printed before hV_HAL_exit(1) is called.
- Debugging shows that hV_HAL_SPI3_read() reads an unexpected value from OTP memory.
- Library developers noted that certain ESP32 boards may crash due to incorrect pin definitions, though our board is not explicitly mentioned.
- This issue was not present in version 7.x of PDLS_Basic, which did not include this OTP check.

Hardware Setup & Pin Connections:
Using the ESP32 Dev Module configuration in the Arduino IDE with the following pin assignments:
```
const pins_t boardESP32DevKitC = {
    .panelBusy = 27,        // EXT3 pin 3 (Red) -> GPIO27
    .panelDC = 26,          // EXT3 pin 4 (Orange) -> GPIO26
    .panelReset = 25,       // EXT3 pin 5 (Yellow) -> GPIO25
    .flashCS = 33,          // EXT3 pin 8 (Violet) -> GPIO33
    .panelCS = 32,          // EXT3 pin 9 (Grey) -> GPIO32
    .panelCSS = NOT_CONNECTED,
    .flashCSS = NOT_CONNECTED,
    .touchReset = NOT_CONNECTED,
    .touchInt = NOT_CONNECTED,
    .cardCS = NOT_CONNECTED,
    .cardDetect = NOT_CONNECTED,
};
```
Troubleshooting Attempts:

- Cross-referenced pin assignments between Freenove ESP32 and Espressif ESP32 Devkit-C.
- Tried forcing SPI to specific GPIOs:
`SPI.begin(18, 19, 23, 32);  // SCK, MISO, MOSI, CS
`

Should I disable the OTP check in the library to allow initialization with this specific board? OTP checks were not present in the 7.0 version of the library - when I initially tested this module. Or is there a way to force PDLS_Basic to use manual SPI pins instead of defaulting to VSPI? I am open to going back to version 7.x.x, but need to know which versions of dependent libraries to use as well.

**Comment by rei-vilo** [comment]
Thank you for the very detailed submission. It helps a lot.

Each screen includes parameters stored in the ROM of the screen controller, called OTP, and customised to ensure optimal image quality. Earlier releases of PDLS didn't read those parameters but used standard values instead.

The screen controller uses a 3-wire SPI: clock, data (MOSI + MISO) and chip select. As Arduino does not feature 3-wire SPI, it is bit-banged. This could be the issue, especially with an ESP32 MCUs, which are very tricky. 

I don't have the [Freenove ESP32-WROOM Board](https://store.freenove.com/products/fnk0090) so I am going to use the [ESP32 Pico Board v4.1 board](https://docs.espressif.com/projects/esp-idf/en/v4.4/esp32/hw-reference/esp32/get-started-pico-kit.html#get-started-pico-kit-v4-board-front) instead to perform the tests and replicate the issue.

**Comment by rei-vilo** [comment]
Thank you for the very detailed submission. It helps a lot.

Each screen includes parameters stored in the ROM of the screen controller, called OTP, and customised to ensure optimal image quality. Earlier releases of PDLS didn't read those parameters but used standard values instead.

The screen controller uses a 3-wire SPI: clock, data (MOSI + MISO) and chip select. As Arduino does not feature 3-wire SPI, it is bit-banged. This could be the issue, especially with an ESP32 MCUs, which are very tricky. 

I don't have the [Freenove ESP32-WROOM Board](https://store.freenove.com/products/fnk0090) so I am going to use the [ESP32 Pico Board v4.1 board](https://docs.espressif.com/projects/esp-idf/en/v4.4/esp32/hw-reference/esp32/get-started-pico-kit.html#get-started-pico-kit-v4-board-front) instead to perform the tests and replicate the issue.

Have you tried a basic example of the driver from **Files > Examples > Pervasive_Wide_Small > DemoNEW**?

**Comment by rei-vilo** [comment]
The ESP32 MCUs require a specific initialisation of SPI, as done in [lines 165 sq.](https://github.com/rei-vilo/PDLS_Common/blob/main/src/hV_HAL_Peripherals.cpp#L165) of **hV_HAL_Peripherals**.

``` cpp
#elif defined(ARDUINO_ESP32_PICO)

        // Board ESP32-Pico-DevKitM-2 crashes if pins are not specified.
        SPI.begin(14, 12, 13); // SCK MISO MOSI
```

Currently, `ARDUINO_XIAO_ESP32C3` and `ARDUINO_ESP32_PICO` are tested, plus a generic `ARDUINO_ARCH_ESP32`.

It happened that the initialisation of the bit-banged 3-wire SPI, as done in [lines 79 sq.](https://github.com/rei-vilo/PDLS_Common/blob/c0c6d5afc0d8511838965a704b6faaf3d10c3ba4/src/hV_HAL_Peripherals.cpp#L79) of **hV_HAL_Peripherals** wasn't performed correctly. 

``` cpp
#elif defined(ARDUINO_ESP32_PICO)

    // void begin(int8_t sck=-1, int8_t miso=-1, int8_t mosi=-1, int8_t ss=-1);
    // Board ESP32-Pico-DevKitM-2 crashes if pins are not specified.
    // hV_HAL_SPI.begin(14, 12, 13); // SCK MISO MOSI
    hV_HAL_SPI3_define(14, 13); // SCK SDA=MOSI
```

It is fixed and tested now.

The fixes are included in release 9.0.7 of [PDLS_Common](https://github.com/rei-vilo/PDLS_Common/releases/tag/9.0.7).

**Comment by illyaom19** [comment]
Unfortunately that still doesn't fix the issue for the ESP32-WROOM-32E, which is what my Freenove ESP32 WROOM board has.

My board is set to "ESP32 Dev Module" in the Arduino IDE, so I am expecting a `ARDUINO_ARCH_ESP32` board macro to be defined. My SPI is connected to my board's HSPI, which are pins 12, 13, 14, which aligns with your changes in 9.0.7. For reference, VSPI would be pins 5, 18, 19.

Attached is my board's pinout: 

![Image](https://github.com/user-attachments/assets/7602ce86-be88-4b20-a553-66a1f9460ec3)

Using library versions before the OTP change (7.0.4):

- KS0C works with the EXT3.1 connected through HSPI
  - **NO** fast update (since there are no display definitions for a KS0C, only KS09 and PS09 - different drivers and the display doesn't work). 
- Switching wires to VSPI causes the screen not to initialize, so I am guessing my ESP32 defaults to HSPI.

I require fast update to work for my use case, but my board won't do the OTP check, and the old libraries don't have support for the 0C.

**Comment by illyaom19** [comment]
Noting that I will be testing this with an ESP32-S3-DevKitC-1 when it comes in as that will be what I am trying to integrate the EPD with. That uses a ESP32-S3-WROOM-1-N8R8 processor which has configurable SPI pins, so I think the `SPI.begin(14, 12, 13);` line in **hV_HAL_Peripherals** should work.

**Comment by rei-vilo** [comment]
I managed to get a **ESP32 Core Board v2** powered by an ESP-WROOM-32 to test. 

I used the `boardESP32DevKitC` configuration with the following connections.

``` cpp
Pervasive_Wide_Small myDriver(eScreen_EPD_271_KS_0C, boardESP32DevKitC);
```

![](https://embeddedcomputing.weebly.com/uploads/1/1/6/2/11624344/ext3-esp32-devkitc-1_orig.png)

Everything works as expected. Below is the trace. 

```
=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2025.03.05 10:08:23 =~=~=~=~=~=~=~=~=~=~=~=
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4916
load:0x40078000,len:16492
load:0x40080400,len:4
load:0x40080404,len:3524
entry 0x400805b8

hV _ Begin

hV _ PDLS_Basic_Sketch.ino
hV _ Mar  5 2025 10:04:08

hV _ OTP check passed - Bank 0, first 0xa5 as expected
hV _ Screen iTC 2.71"-Wide iT
hV _ Size 176x264
hV _ Number 271-KS-0C
hV _ Driver Wide small v9.0.3
hV _ PDLS Basic v9.0.6

hV _ DISPLAY_WHOAMI
 > 8  
 > 7  
 > 6  
 > 5  
 > 4  
 > 3  
 > 2  
 > 1  
         
hV _ Clear or regenerate
hV _ Exit with code 0  
```

Have you considered using a logic analyser to check the signals?
